// <auto-generated />
using System;
using FormBuilder.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormBuilder.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("FormBuilder.Api.Models.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActionAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ApprovalStepId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Approver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormSubmissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStepId");

                    b.HasIndex("FormSubmissionId");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("FormBuilder.Api.Models.ApprovalStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Approver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FormTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormTemplateId");

                    b.ToTable("ApprovalSteps");
                });

            modelBuilder.Entity("FormBuilder.Api.Models.FormField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FormTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormTemplateId");

                    b.ToTable("FormFields");
                });

            modelBuilder.Entity("FormBuilder.Api.Models.FormSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FormTemplateId");

                    b.ToTable("FormSubmissions");
                });

            modelBuilder.Entity("FormBuilder.Api.Models.FormTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FormTemplates");
                });

            modelBuilder.Entity("FormBuilder.Api.Models.SubmissionValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormSubmissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FormFieldId");

                    b.HasIndex("FormSubmissionId");

                    b.ToTable("SubmissionValues");
                });

            modelBuilder.Entity("FormBuilder.Api.Models.Approval", b =>
                {
                    b.HasOne("FormBuilder.Api.Models.ApprovalStep", "ApprovalStep")
                        .WithMany("Approvals")
                        .HasForeignKey("ApprovalStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormBuilder.Api.Models.FormSubmission", "FormSubmission")
                        .WithMany("Approvals")
                        .HasForeignKey("FormSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalStep");

                    b.Navigation("FormSubmission");
                });

            modelBuilder.Entity("FormBuilder.Api.Models.ApprovalStep", b =>
                {
                    b.HasOne("FormBuilder.Api.Models.FormTemplate", "FormTemplate")
                        .WithMany("ApprovalSteps")
                        .HasForeignKey("FormTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormTemplate");
                });

            modelBuilder.Entity("FormBuilder.Api.Models.FormField", b =>
                {
                    b.HasOne("FormBuilder.Api.Models.FormTemplate", "FormTemplate")
                        .WithMany("Fields")
                        .HasForeignKey("FormTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormTemplate");
                });

            modelBuilder.Entity("FormBuilder.Api.Models.FormSubmission", b =>
                {
                    b.HasOne("FormBuilder.Api.Models.FormTemplate", "FormTemplate")
                        .WithMany("Submissions")
                        .HasForeignKey("FormTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormTemplate");
                });

            modelBuilder.Entity("FormBuilder.Api.Models.SubmissionValue", b =>
                {
                    b.HasOne("FormBuilder.Api.Models.FormField", "FormField")
                        .WithMany("SubmissionValues")
                        .HasForeignKey("FormFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormBuilder.Api.Models.FormSubmission", "FormSubmission")
                        .WithMany("Values")
                        .HasForeignKey("FormSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormField");

                    b.Navigation("FormSubmission");
                });

            modelBuilder.Entity("FormBuilder.Api.Models.ApprovalStep", b =>
                {
                    b.Navigation("Approvals");
                });

            modelBuilder.Entity("FormBuilder.Api.Models.FormField", b =>
                {
                    b.Navigation("SubmissionValues");
                });

            modelBuilder.Entity("FormBuilder.Api.Models.FormSubmission", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("FormBuilder.Api.Models.FormTemplate", b =>
                {
                    b.Navigation("ApprovalSteps");

                    b.Navigation("Fields");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
